//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTourism
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachDangKy
    {
        public string MaTaiKhoan { get; set; }
        public string MaChuyenDi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual LichTrinh LichTrinh { get; set; }
    }
}
