//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTourism
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class software2023Entities : DbContext
    {
        public software2023Entities()
            : base("name=software2023Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<ChuyenDi> ChuyenDis { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhSachDangKy> DanhSachDangKies { get; set; }
        public virtual DbSet<DanhSachDuKhach> DanhSachDuKhaches { get; set; }
        public virtual DbSet<HuongDanVien> HuongDanViens { get; set; }
        public virtual DbSet<LichTrinh> LichTrinhs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinCaNhan> ThongTinCaNhans { get; set; }
        public virtual DbSet<YeuCau> YeuCaus { get; set; }
    }
}
